# Generated by Django 2.1.5 on 2019-02-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_edited',
            field=models.DateField(auto_now=True),
        ),
    ]
