# Generated by Django 2.1.5 on 2019-01-11 23:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0018_auto_20190111_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('image_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None)),
                ('date', models.DateField()),
                ('election_area_type', models.CharField(choices=[('State', 'State'), ('National', 'National'), ('None', 'None')], default='None', max_length=10)),
                ('last_edited', models.DateField(auto_now=True)),
                ('candidates', models.ManyToManyField(related_name='elections', to='candidates.Candidate')),
            ],
        ),
    ]
