# Generated by Django 2.1.5 on 2019-01-26 07:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('image_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('State', 'State'), ('National', 'National'), ('None', 'None')], default='None', max_length=10)),
                ('state', models.CharField(choices=[('None', 'None'), ('Alaska', 'Alaska'), ('Alabama', 'Alabama'), ('Arkansas', 'Arkansas'), ('American Samoa', 'American Samoa'), ('Arizona', 'Arizona'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('District of Columbia', 'District of Columbia'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Guam', 'Guam'), ('Hawaii', 'Hawaii'), ('Iowa', 'Iowa'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Massachusetts', 'Massachusetts'), ('Maryland', 'Maryland'), ('Maine', 'Maine'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Missouri', 'Missouri'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Mississippi', 'Mississippi'), ('Montana', 'Montana'), ('National', 'National'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Nebraska', 'Nebraska'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('Nevada', 'Nevada'), ('New York', 'New York'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Puerto Rico', 'Puerto Rico'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Virginia', 'Virginia'), ('Virgin Islands', 'Virgin Islands'), ('Vermont', 'Vermont'), ('Washington', 'Washington'), ('Wisconsin', 'Wisconsin'), ('West Virginia', 'West Virginia'), ('Wyoming', 'Wyoming')], default='None', max_length=20)),
                ('last_edited', models.DateField(auto_now=True)),
                ('candidates', models.ManyToManyField(related_name='elections', to='candidates.Candidate')),
            ],
        ),
    ]
