# Generated by Django 2.1.5 on 2019-01-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='election_area_type',
            new_name='type',
        ),
    ]
