# Generated by Django 2.1.5 on 2019-01-31 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('serving_length', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='candidaterole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.Role'),
        ),
    ]
