# Generated by Django 2.1.5 on 2019-01-31 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_auto_20190131_1804'),
        ('candidates', '0002_auto_20190127_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.CandidateRole'),
        ),
    ]
