# Generated by Django 2.1.5 on 2019-02-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='role',
        ),
    ]
