# Generated by Django 2.1.5 on 2019-01-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_auto_20190107_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newcandidate',
            old_name='name',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='newelection',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='newcandidate',
            name='cover_image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='newcandidate',
            name='last',
            field=models.CharField(default='last_name', max_length=200),
            preserve_default=False,
        ),
    ]
