# Generated by Django 2.1.5 on 2019-01-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_auto_20190107_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='newelection',
            name='candidates',
            field=models.ManyToManyField(to='candidates.NewCandidate'),
        ),
        migrations.AddField(
            model_name='newelection',
            name='cover_image_url',
            field=models.URLField(null=True),
        ),
    ]
