# Generated by Django 2.1.5 on 2019-01-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_auto_20190107_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='newcandidate',
            name='sections',
            field=models.ManyToManyField(to='candidates.NewSection'),
        ),
    ]
