# Generated by Django 2.1.5 on 2019-01-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_auto_20190107_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcandidate',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
