# Generated by Django 2.1.5 on 2019-01-09 19:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_auto_20190108_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcandidate',
            name='sections',
        ),
        migrations.AddField(
            model_name='newcandidate',
            name='image_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), null=True, size=None),
        ),
    ]
