# Generated by Django 2.1.5 on 2019-01-09 19:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_auto_20190109_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcandidate',
            name='test',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
    ]
