# Generated by Django 2.1.5 on 2019-01-09 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_auto_20190109_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsection',
            name='test',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='candidates.NewCandidate'),
        ),
    ]
