# Generated by Django 2.1.5 on 2019-01-10 22:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_newsection_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcandidate',
            name='test',
        ),
        migrations.AddField(
            model_name='newelection',
            name='image_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='newsection',
            name='test',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='candidates.NewCandidate'),
        ),
    ]
