# Generated by Django 2.1.5 on 2019-01-11 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('candidates', '0012_auto_20190110_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsection',
            name='test',
        ),
        migrations.AddField(
            model_name='newsection',
            name='content_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsection',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
