# Generated by Django 2.1.5 on 2019-01-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_auto_20190111_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='newelection',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
