# Generated by Django 2.1.5 on 2019-01-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_auto_20190111_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newelection',
            name='date',
            field=models.DateField(),
        ),
    ]
