# Generated by Django 2.1.5 on 2019-01-21 23:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        ('candidates', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('candidates', models.ManyToManyField(blank=True, related_name='contributors', to='candidates.Candidate')),
                ('elections', models.ManyToManyField(blank=True, related_name='contributors', to='elections.Election')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionInfoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('image_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None)),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('State', 'State'), ('National', 'National'), ('None', 'None')], default='None', max_length=10, null=True)),
                ('last_edited', models.DateField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('candidates', models.ManyToManyField(blank=True, related_name='info_request_elections', to='candidates.Candidate')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
