# Generated by Django 2.1.5 on 2019-01-22 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoRequests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electioninforequest',
            name='candidates',
        ),
        migrations.RemoveField(
            model_name='electioninforequest',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ElectionInfoRequest',
        ),
    ]
