# Generated by Django 2.1.5 on 2019-01-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoRequests', '0002_auto_20190122_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='email',
            field=models.EmailField(default='ethanpippin2343@gmail.com', max_length=50),
            preserve_default=False,
        ),
    ]
