# Generated by Django 2.1.5 on 2019-01-26 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoRequests', '0005_candidateinforequest_electioninforequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateinforequest',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='candidateinforequest',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='inforequest',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='inforequest',
            name='contributor',
        ),
        migrations.DeleteModel(
            name='CandidateInfoRequest',
        ),
        migrations.DeleteModel(
            name='InfoRequest',
        ),
    ]
