# Generated by Django 2.1.5 on 2019-01-26 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infoRequests', '0008_auto_20190126_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electioninforequest',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infoRequests.Contributor'),
        ),
    ]
