# Generated by Django 2.1.5 on 2019-01-26 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infoRequests', '0009_auto_20190126_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinforequest',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infoRequests', to='candidates.Candidate'),
        ),
    ]
