# Generated by Django 2.1.5 on 2019-01-26 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infoRequests', '0010_auto_20190126_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinforequest',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidateInfoRequests', to='infoRequests.Contributor'),
        ),
        migrations.AlterField(
            model_name='electioninforequest',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electionInfoRequests', to='infoRequests.Contributor'),
        ),
        migrations.AlterField(
            model_name='electioninforequest',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infoRequests', to='elections.Election'),
        ),
    ]
